name: AWattPrice
options:
  deploymentTarget:
    iOS: "14.0"
  postGenCommand: |
    bundle install
    open AWattPrice.xcodeproj
  defaultConfig:
    Development Test Staging

configs:
  # Use Development or Distribution to select if the configuration should be associated with the Development or Distribution certificate.
  # Use the name in the middle to specify the name of the configuration.
  # Use Staging or Production to specify the type of configuration.
  # Assign debug or release, that xcodegen can configure some standard settings for the type of configuration. Staging basically means debug and Production means release, just used other names. 
  
  # A distinction between Staging and Production is needed as it specifies if the "me.space8.AWattPrice.staging" or "me.space8.AWattPrice" bundle id should be used when signing. For example this allows to sign an app for AdHoc with either the staging bundle id or the production bundle id. 
  Development Test Staging: debug
  Development Test Production: release
  Distribution AdHoc Staging: debug
  Distribution AdHoc Production: release
  Distribution AppStore Staging: debug
  Distribution AppStore Production: release

settings:
  base:
    DEVELOPMENT_TEAM: RC32A2AMHF
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

packages:
  Resolver:
    url: git@github.com:hmlongco/Resolver.git
    majorVersion: 1.4.3

targets:
  AWattPrice:
    type: application
    platform: iOS
    
    scheme:
      configVariantes:
        - Test
        - AdHoc
        - AppStore
    
    sources:
      - path: AWattPrice
        configFiles:
          Development Test Staging: AWattPrice/Staging.xcconfig
          Development Test Production: AWattprice/Production.xcconfig
          Distribution AdHoc Staging: AWattPrice/Staging.xcconfig
          Distribution AdHoc Production: AWattPrice/Production.xcconfig
          Distribution AppStore Staging: AWattPrice/Staging.xcconfig
          Distribution AppStore Production: AWattprice/Production.xcconfig
        
    settings:
      base:
        INFOPLIST_FILE: AWattPrice/Info.plist
        DEVELOPMENT_ASSET_PATHS:
          - AWattPrice/Resources/Preview\ Content
        CODE_SIGN_ENTITLEMENTS: AWattPrice/AWattPrice.entitlements
      configs:
        development:
          CODE_SIGN_IDENTITY: "Apple Development"
        distribution:
          CODE_SIGN_IDENTITY: "Apple Distribution"
        staging:
          PRODUCT_BUNDLE_IDENTIFIER: me.space8.AWattPrice.staging
        production:
          PRODUCT_BUNDLE_IDENTIFIER: me.space8.AWattPrice
        Development Test Staging:
          PROVISIONING_PROFILE_SPECIFIER: match Development me.space8.AWattPrice.staging
        Development Test Production:
          PROVISIONING_PROFILE_SPECIFIER: match Development me.space8.AWattPrice
        Distribution AdHoc Staging:
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc me.space8.AWattPrice.staging
        Distribution AdHoc Production:
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc me.space8.AWattPrice
        Distribution AppStore Staging:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore me.space8.AWattPrice.staging
        Distribution AppStore Production:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore me.space8.AWattPrice
          
    dependencies:
      - package: Resolver