# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier("me.space8.AWattPrice")
skip_binary_upload(true)
overwrite_screenshots(true)
automatic_release(true)
