# Ruby syntax highlighting

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    prompt_increment_marketing_number
    prompt_increment_build_number
    build_app(scheme: "AWattPrice", configuration: "Distribution AppStore Production")
    upload_to_testflight(app_identifier: "me.space8.AWattPrice", skip_submission: true, skip_waiting_for_build_processing: true)
  end
  
  lane :screenshots do
    capture_screenshots
    frame_screenshots(path: "./fastlane/screenshots/")
    deliver(app_version: "2.0.1")
  end
end

